project_id = "shskknkivuewuqonjdjc"

[functions.sync-booking-systems]
verify_jwt = true

[functions.webhook-receiver]
verify_jwt = false

[functions.process-inbound-queue]
verify_jwt = true

[functions.process-outbound-queue]
verify_jwt = true

[functions.process-call]
verify_jwt = true

[functions.process-call-lovable]
verify_jwt = true

[functions.process-queue]
verify_jwt = true

[functions.delete-user-data]
verify_jwt = true

[functions.leaddesk-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = false

[functions.decrypt-data]
verify_jwt = true

[functions.create-payment-session]
verify_jwt = true

[functions.stripe-payment-webhook]
verify_jwt = false