project_id = "shskknkivuewuqonjdjc"

[functions.process-call]
verify_jwt = false

[functions.process-call-lovable]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.delete-user-data]
verify_jwt = true

[functions.leaddesk-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = false

[functions.decrypt-data]
verify_jwt = true
